# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x03\x61sr\"!\n\nAudioChunk\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\"A\n\x0b\x41SRResponse\x12\x10\n\x08start_ts\x18\x01 \x01(\x02\x12\x0e\n\x06\x65nd_ts\x18\x02 \x01(\x02\x12\x10\n\x08sentence\x18\x03 \x01(\t2;\n\x03\x41SR\x12\x34\n\x0bStreamAudio\x12\x0f.asr.AudioChunk\x1a\x10.asr.ASRResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=18
  _globals['_AUDIOCHUNK']._serialized_end=51
  _globals['_ASRRESPONSE']._serialized_start=53
  _globals['_ASRRESPONSE']._serialized_end=118
  _globals['_ASR']._serialized_start=120
  _globals['_ASR']._serialized_end=179
# @@protoc_insertion_point(module_scope)
